services:
  cat-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cat-backend
    restart: always
    ports:
      - 9350:3000
    environment:
      MYSQL_HOST: mysql-cats
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cats_db
    networks:
      cat_network:
        aliases:
          - cat-backend
    depends_on:
      - mysql-cats


  mysql-cats:
    image: mysql:latest
    container_name: mysql-cats
    restart: always
    volumes:
      - mysql-cats:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cats_db
    networks:
      cat_network:
        aliases:
          - mysql-cats

volumes:
  mysql-cats:

networks:
  cat_network:
    driver: bridge